### ISSUE TITLE
UWP DFU library

### ISSUE THREAD

**Issue by jessenic** [NordicSemiconductor/Windows-nRF-Toolbox#2]
Are you working on an Universal Windows Platform DFU library for Windows 10 devices? I am using Windows 10 IoT Core device as a gateway for my nRF52-based devices and I'd like to implement DFU on it. UWP library would also work on the destkop and mobile versions of Windows 10.

**Comment by jovirus** [comment]
Hey @jessenic 
Thank you for following Nordic open source project.
I am sorry to say that we currently do not support the Windows Runtime Api to access bluetooth hardware. However, we have pc version of ble driver, which you can run crossed on Windows, OSX, Linux based. See more detail at https://github.com/NordicSemiconductor/pc-ble-driver

Also in this repository you can use our Legacy DFU, which is supported on softdevice S110

Have a great day

**Comment by jovirus** [comment]
@jessenic This is the implementation of dfu in java script, https://github.com/NordicSemiconductor/pc-ble-driver-js/tree/dfu/api/dfu which support security dfu
