### ISSUE TITLE
How to install nrFToolBox for WindowsPhone?

### ISSUE THREAD

**Issue by Fran6J** [NordicSemiconductor/Windows-nRF-Toolbox#3]
Hi,
May be this is my misunderstanding, so sorry for my ignorance. I would like get nrFToolBox on my WindowsPhone, but how can I use this files to get this application on my WP Lumia 640LTE? 
I have my own nrF51822 hardware with a basic test application to send data with NUS service, I can see received this data on my PC with the Nordic dongle and nRFUart application. I would like see this data on my smartphone with a nRFUart for WindowsPhone.

**Comment by jovirus** [comment]
@Fran6J 
Thank you for using Nordic products. The nRF Toolbox for Windows Phone is currently removed from Windows Phone store and we are unable to maintain it any longer. However, you can use this repository to install to your phone. 

Jiajun Qiu

**Comment by Fran6J** [comment]
Hi,
Thank you very much jovirus. I seen the application is not on the windowsphone store. But with my some skills close to the hardware, not close to this kind of platform, I don't know how to use this repository to install nRFToolBox on Windows Phone (WP8.1).
Probably my best way to get NrfToolBox on smartphone is to invest in a Android smartphone... :(
Francis

**Comment by jovirus** [comment]
@Fran6J 
We have nRF Toolbox for iOS and Android, and both of them are open source.
You can find them under the NordicSemiconductor.

Jiajun Qiu

**Comment by Fran6J** [comment]
ok thanks
