### ISSUE TITLE
Hii have a question about this repository. 

### ISSUE THREAD

**Issue by kwongiho** [NordicSemiconductor/Windows-nRF-Toolbox#4]
Hi genius guys.
Im a junior developer who is making DFU software for windows 10.
I saw this repository and realised that the library provided by nRF has stopped its services 2 years ago.

But we required DFU for Windows 10 to use C#. 

Perhaps, do you think that I can develop a DFU version for Window with only this document?

Thanks for reading :')

**Comment by jovirus** [comment]
Hi @KwonGiho 
Thank you for contacting us.
You can make changes based on the DFU lib on Windows, however we are no longer able to give you support on this library.

For implement the DFU, you find the reference [here](http://developer.nordicsemi.com/nRF5_SDK/) 

Nordic Semiconductor
